"""empty message

Revision ID: 268e5d5ff664
Revises: 828a000aad2a
Create Date: 2026-04-04 09:05:24.525641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '268e5d5ff664'
down_revision = '828a000aad2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_nave',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nave',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('dimension', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nave')
    op.drop_table('favorite_nave')
    # ### end Alembic commands ###
